/* Dynamic color variables generated by Blade (Content-Type: text/css) */
:root {
    --site-primary:   {{ config('app.primary_color', '#F5BF23') }};
    --site-secondary: {{ config('app.secondary_color', '#292929') }};
    --site-dark:      {{ config('app.dark_color', '#222222') }};
    --site-hover:     {{ config('app.accent_hover_color', '#222222') }};
    /* Derived shades */
    --site-primary-alpha: {{ config('app.primary_color', '#F5BF23') }}33;
}
